#!/usr/bin/env python3
# file: scripts/offset_finder.py
# Re-derive Standoff 2 offsets after a game update using Il2CppDumper output
# Usage: python3 offset_finder.py --dump /path/to/dump.cs --il2cpp /path/to/il2cpp.h
#
# Prerequisites:
#   Il2CppDumper: https://github.com/Perfare/Il2CppDumper
#   Run against the current APK's libil2cpp.so + global-metadata.dat
#   Then run this script against the dump output

import re
import sys
import argparse
from pathlib import Path

def parse_dump(dump_cs: str) -> dict:
    """Parse Il2CppDumper dump.cs into {class: {field: offset}} map."""
    classes = {}
    current_class = None
    for line in dump_cs.splitlines():
        # Class declaration
        m = re.match(r'^\s*(public |private |sealed )*class (\w+)', line)
        if m:
            current_class = m.group(2)
            classes[current_class] = {}
            continue
        # Field with offset comment: // 0x68
        m = re.match(r'^\s+(?:private|public|protected)?\s*[\w<>\[\]]+\s+(\w+);\s*//\s*(0x[0-9a-fA-F]+)', line)
        if m and current_class:
            field, offset = m.group(1), int(m.group(2), 16)
            classes[current_class][field] = offset
    return classes

def parse_il2cpp_header(header: str) -> dict:
    """Parse il2cpp.h for method RVAs: {ClassName_MethodName: rva}."""
    methods = {}
    for line in header.splitlines():
        # extern void* ClassName$$MethodName (void* __this, ...) // RVA: 0x...
        m = re.match(r'extern\s+\S+\s+(\w+)\$\$(\w+)\s*\(.*\)\s*//\s*RVA:\s*(0x[0-9a-fA-F]+)', line)
        if m:
            key = f"{m.group(1)}::{m.group(2)}"
            methods[key] = int(m.group(3), 16)
    return methods

TARGETS = {
    "classes": {
        "PlayerController": ["health","max_health","team","isAlive","playerName",
                              "transform","animator","weaponController","isLocal",
                              "characterController"],
        "WeaponController": ["currentWeapon","fireRate","nextFireTime","spread",
                             "recoilX","recoilY","ammoInClip","ammoInReserve","weaponType"],
        "GameManager":      ["_instance","playerList","localPlayer","isGameActive","roundTime"],
    },
    "methods": {
        "PlayerController": ["Update","TakeDamage"],
        "WeaponController": ["FireRaycast"],
        "CharacterController": ["SimpleMove"],
        "FlashedEffect": ["UpdateFlashAmount"],
        "SmokeEffect": ["Show"],
    }
}

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dump",    required=True)
    parser.add_argument("--il2cpp",  required=True)
    parser.add_argument("--out",     default="offsets_new.hpp")
    args = parser.parse_args()

    dump_cs  = Path(args.dump).read_text(errors="replace")
    il2cpp_h = Path(args.il2cpp).read_text(errors="replace")

    classes = parse_dump(dump_cs)
    methods = parse_il2cpp_header(il2cpp_h)

    lines = [
        "// AUTO-GENERATED by offset_finder.py — replace in shared/offsets.hpp",
        f"// Source: {args.dump}",
        "#pragma once\n",
        "namespace Offsets {\n",
    ]

    for cls_name, fields in TARGETS["classes"].items():
        cls_data = classes.get(cls_name, {})
        lines.append(f"    namespace {cls_name} {{")
        for field in fields:
            offset = cls_data.get(field, cls_data.get(field.lower(), None))
            if offset is not None:
                lines.append(f"        constexpr uintptr_t {field:<20} = 0x{offset:X};")
            else:
                lines.append(f"        // constexpr uintptr_t {field} = ???;  // NOT FOUND")
        lines.append("    }\n")

    lines.append("}\n\nnamespace MethodRVAs {\n")
    for cls_name, meths in TARGETS["methods"].items():
        lines.append(f"    // {cls_name}")
        for meth in meths:
            key = f"{cls_name}::{meth}"
            rva = methods.get(key)
            if rva:
                lines.append(f"    constexpr uintptr_t {cls_name}_{meth:<20} = 0x{rva:X};")
            else:
                lines.append(f"    // constexpr uintptr_t {cls_name}_{meth} = ???;  // NOT FOUND")
    lines.append("}\n")

    out_text = "\n".join(lines)
    Path(args.out).write_text(out_text)
    print(f"[+] Written to {args.out}")
    print("    Review ???-marked entries manually in Ghidra")

if __name__ == "__main__":
    main()
